- name: 1. 基礎建設 (Juju 供應 OS)
  hosts: maasjuju
  gather_facts: no
  vars:
    bm_model: "os-only"
    target_os: "ubuntu@24.04"
    # 硬體標籤定義
    tags: "tags=slurm-node"

  tasks:
    - name: 1.1 初始化環境
      shell: |
        juju add-model {{ bm_model }} || true
        # 請求 Machine 0 (Master)
        juju add-machine -m {{ bm_model }} --constraints {{ tags }} --base {{ target_os }}
