---
- name: Deploy K8s and Auto-Register to KubeSphere
  hosts: all
  gather_facts: no
  vars:
    # --- 變數設定 ---
    k8s_model: "k8s-cluster-auto"
    ks_url: "http://192.168.1.112:30880"
    ks_user: "admin"
    ks_password: "P@88w0rd"  # <--- 記得改成您的密碼

  tasks:
    # ---------------------------------------------------------
    # 第一階段：Juju 部署與設定檔獲取
    # ---------------------------------------------------------
    
    # 【新增】這一步被我漏掉了，必須先建立模型！
    - name: 1.1 Create Juju Model
      command: "juju add-model {{ k8s_model }}"
      ignore_errors: yes # 如果模型已存在，忽略錯誤繼續

    # 【新增】設定該模型預設使用 Ubuntu 22.04 (避免 Juju 版本警告)
    - name: 1.2 Set Model Base to Ubuntu 22.04
      command: "juju model-config -m {{ k8s_model }} default-base=ubuntu@22.04"
      ignore_errors: yes

    - name: 1.3 Deploy MicroK8s
      # 這裡加上 --base ubuntu@22.04 是新版 Juju 的標準寫法 (取代 --series)
      command: "juju deploy microk8s --channel=1.28/stable --base ubuntu@22.04 -m {{ k8s_model }}"
      ignore_errors: yes 

    - name: 2. Wait for MicroK8s to be Ready
      command: "juju wait-for application microk8s -m {{ k8s_model }} --query='name==\"microk8s\" && status==\"active\"'"
      # 這一步會等比較久 (OS 安裝 + K8s 安裝)

    - name: 3. Get Node Public IPv4
      command: "juju ssh -m {{ k8s_model }} microk8s/0 -- ip -4 -o addr show scope global"
      register: ip_result

    - name: 4. Parse IP Address
      set_fact:
        node_ip: "{{ ip_result.stdout | regex_search('inet ([0-9.]+)', '\\1') | first }}"

    - name: 5. Get and Patch Kubeconfig
      command: "juju ssh -m {{ k8s_model }} microk8s/0 -- sudo microk8s config | sed 's/127.0.0.1/{{ node_ip }}/g'"
      register: kubeconfig_patched

    # ---------------------------------------------------------
    # 第二階段：KubeSphere 自動納管 (API 操作)
    # ---------------------------------------------------------
    - name: 6. Login to KubeSphere API (Get Token)
      uri:
        url: "{{ ks_url }}/kapis/iam.kubesphere.io/v1alpha2/login"
        method: POST
        body_format: json
        body:
          username: "{{ ks_user }}"
          password: "{{ ks_password }}"
        validate_certs: no
      register: ks_login_response
      delegate_to: localhost 

    - name: 7. Register Cluster to KubeSphere
      uri:
        url: "{{ ks_url }}/kapis/cluster.kubesphere.io/v1alpha1/clusters"
        method: POST
        body_format: json
        headers:
          Authorization: "Bearer {{ ks_login_response.json.access_token }}"
        body:
          apiVersion: "cluster.kubesphere.io/v1alpha1"
          kind: "Cluster"
          metadata:
            name: "{{ k8s_model }}"
            labels:
              cluster-role.kubesphere.io/member: ""
          spec:
            connection:
              type: "direct"
              kubeconfig: "{{ kubeconfig_patched.stdout | b64encode }}"
            provider: "microk8s"
        status_code: [200, 201, 409] # 409 代表已存在 (不報錯)
        validate_certs: no
      delegate_to: localhost

    - name: Final Status
      debug:
        msg: "成功！集群 {{ k8s_model }} 已部署並自動註冊至 KubeSphere。"
