---
- name: Deploy K8s and Auto-Register to KubeSphere
  hosts: all
  gather_facts: no
  vars:
    # --- è®Šæ•¸è¨­å®š ---
    k8s_model: "k8s-cluster-auto"
    ks_url: "http://192.168.1.112:30880"
    ks_user: "admin"
    ks_password: "1qaz@WSX"  # <-- è«‹ç¢ºèªé€™çµ„å¯†ç¢¼

  tasks:
    # ... (çœç•¥ Task 1 ~ 5) ...

    # ---------------------------------------------------------
    # ã€å¾©æ´» Task 6ã€‘å†æ¬¡å˜—è©¦ç™»å…¥ï¼Œä¸¦å–å¾— Token
    # ---------------------------------------------------------
    - name: 6. Login to KubeSphere API (Get Token)
      uri:
        url: "{{ ks_url }}/kapis/iam.kubesphere.io/v1alpha2/login"
        method: POST
        body_format: json
        body:
          username: "{{ ks_user }}"
          password: "{{ ks_password }}"
        
        # ä½¿ç”¨ url_username/url_password ç¢ºä¿æ†‘è­‰åœ¨ Header ä¸­å‚³è¼¸
        url_username: "{{ ks_user }}"
        url_password: "{{ ks_password }}"
        
        validate_certs: no
        status_code: [200] # å¿…é ˆè¿”å›ž 200 æ‰ç®—æˆåŠŸ
      register: ks_login_response
      delegate_to: localhost 
      # âš ï¸ æ³¨æ„ï¼šå¦‚æžœ Task 6 é‚„æ˜¯å¤±æ•— (403)ï¼Œè«‹ç¢ºèªæ‚¨çš„å¯†ç¢¼ 1qaz@WSX æ˜¯å¦åŒ…å«ç‰¹æ®Šç¬¦è™Ÿï¼Œ
      # æˆ–åœ¨ KubeSphere ç¶²é ä¸Šç¢ºèªå¯†ç¢¼æ˜¯å¦è¢«é‡è¨­ã€‚

    - name: 7. Register Cluster to KubeSphere
      # ã€ä¿®æ­£é‡é»žã€‘ä½¿ç”¨ Task 6 å–å¾—çš„ Token
      uri:
        url: "{{ ks_url }}/kapis/cluster.kubesphere.io/v1alpha1/clusters"
        method: POST
        body_format: json
        headers:
          Authorization: "Bearer {{ ks_login_response.json.access_token }}" # ä½¿ç”¨ Login API è¿”å›žçš„ Token
          Content-Type: "application/json"
        body:
          apiVersion: "cluster.kubesphere.io/v1alpha1"
          kind: "Cluster"
          metadata:
            name: "{{ k8s_model }}"
            labels:
              cluster-role.kubesphere.io/member: ""
          spec:
            connection:
              type: "direct"
              # é€™è£¡çš„ Kubeconfig å¿…é ˆç¶“éŽ Base64 ç·¨ç¢¼ï¼Œæ‰èƒ½ä½œç‚º JSON Body å‚³è¼¸
              kubeconfig: "{{ kubeconfig_patched.stdout | b64encode }}" 
            provider: "microk8s"
        status_code: [201, 409] # æœŸå¾…ç‹€æ…‹ç¢¼ 201 (Created)
        validate_certs: no
      delegate_to: localhost

    - name: Final Status
      debug:
        msg: "ðŸŽ‰ æˆåŠŸï¼é›†ç¾¤ {{ k8s_model }} å·²éƒ¨ç½²ä¸¦è‡ªå‹•è¨»å†Šè‡³ KubeSphereã€‚"
