---
- name: Automate K8s Deployment with Juju (Ubuntu 22.04)
  hosts: all  # 請確保您的 AWX Inventory 指向 Juju Controller
  gather_facts: no
  vars:
    k8s_model: "k8s-cluster-01"

  tasks:
    - name: Create a new Juju Model
      command: "juju add-model {{ k8s_model }}"
      ignore_errors: yes 

    # --- 關鍵修改在此 ---
    - name: Set Model Default Series to Ubuntu 22.04
      # 這一步是雙重保險：確保這個模型裡所有未來的機器都預設用 22.04
      command: "juju model-config -m {{ k8s_model }} default-series=jammy"

    - name: Deploy MicroK8s (Force Ubuntu 22.04)
      # 這裡加上 --series jammy，強制指定 OS 版本
      command: "juju deploy microk8s --channel=1.28/stable --series jammy"
      
    - name: Wait for MicroK8s to be active
      command: "juju status --format=json"
      register: juju_status
      changed_when: false

    - name: Display Status
      debug:
        msg: "Deployment triggered for model {{ k8s_model }} with Ubuntu 22.04 (Jammy)."
