---
- name: Deploy K8s and Auto-Register to KubeSphere
  hosts: all
  gather_facts: no
  vars:
    # --- 變數設定 (AWX Survey 輸入的 k8s_model 會覆蓋這裡) ---
    k8s_model: "k8s-cluster-auto"
    
    # --- KubeSphere 連線資訊 (請確認密碼是否正確) ---
    ks_url: "http://192.168.1.112:30880"
    ks_user: "admin"
    ks_password: "P@88w0rd"  # <--- ⚠️ 請務必確認這裡是您 KubeSphere 的真實密碼

  tasks:
    # =========================================================
    # 第一階段：Juju 部署與設定檔獲取
    # =========================================================
    
    - name: 1.1 Create Juju Model
      command: "juju add-model {{ k8s_model }}"
      ignore_errors: yes # 如果模型已存在，忽略錯誤繼續往下跑

    - name: 1.2 Set Model Base to Ubuntu 22.04
      command: "juju model-config -m {{ k8s_model }} default-base=ubuntu@22.04"
      ignore_errors: yes

    - name: 1.3 Deploy MicroK8s
      # 強制指定 Ubuntu 22.04，避免版本相容問題
      command: "juju deploy microk8s --channel=1.28/stable --base ubuntu@22.04 -m {{ k8s_model }}"
      ignore_errors: yes 

    - name: 2. Wait for MicroK8s to be Ready
      # 這一步會等待直到狀態變成 active (通常需要 5~10 分鐘)
      command: "juju wait-for application microk8s -m {{ k8s_model }} --query='name==\"microk8s\" && status==\"active\"'"

    - name: 3. Get Node Public IPv4
      command:
