---
- name: 5.4 Fix Member Cluster Monitoring (Post-GUI)
  hosts: ks_host
  gather_facts: no
  vars:
    # 預設叢集名稱，您可以根據需要在 AWX 啟動時覆寫此變數
    cluster_name: "{{ k8s_cluster | default('hpc-native-cluster') }}"
    
    # 指向 Member Cluster Kubeconfig 的路徑
    # 請確保這個檔案已經存在於您的 Host Cluster (ks_host) 機器上
    member_cluster_kubeconfig: "/tmp/kubeconfig-{{ cluster_name }}"

  tasks:
    - name: 0. 檢查 Kubeconfig 是否存在
      stat:
        path: "{{ member_cluster_kubeconfig }}"
      register: kubeconfig_file

    - name: 0.1 終止 (如果找不到 Kubeconfig)
      fail:
        msg: "找不到 Kubeconfig 檔案: {{ member_cluster_kubeconfig }}，請檢查路徑或是變數 k8s_cluster 設定。"
      when: not kubeconfig_file.stat.exists

    - name: 1. 等待監控 Namespace 出現 (確保 GUI 安裝已生效)
      shell: |
        kubectl --kubeconfig {{ member_cluster_kubeconfig }} get namespace kubesphere-monitoring-system
      register: ns_check
      until: ns_check.rc == 0
      retries: 20
      delay: 10
      ignore_errors: yes
      # 這會每 10 秒檢查一次，最多等 200 秒，確保 Agent 已經被 Host 推送下去

    - name: 2. 補裝 ServiceMonitor CRD (解決 "no matches for kind" 報錯)
      shell: |
        kubectl --kubeconfig {{ member_cluster_kubeconfig }} apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.68.0/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
      # 如果已經存在，它會顯示 configured，不會報錯

    - name: 3. 注入 GPU 採集規則 (連接 Machine 1 的關鍵)
      shell: |
        cat <<EOF | kubectl --kubeconfig {{ member_cluster_kubeconfig }} apply -f -
        apiVersion: monitoring.coreos.com/v1
        kind: ServiceMonitor
        metadata:
          name: gpu-bridge-monitor
          namespace: kubesphere-monitoring-system
          labels:
            app.kubernetes.io/vendor: kubesphere
        spec:
          selector:
            matchLabels:
              # 這裡對應您在 Machine 1 上部署的 dcgm-exporter Service
              app: dcgm-exporter
          endpoints:
          - port: metrics
            interval: 15s
            path: /metrics
          namespaceSelector:
            matchNames:
            - kubesphere-monitoring-system
        EOF
