# ==========================================
# SKU: HPC-Full-Stack-Reconstruction
# ==========================================
- name: 1. 兩台機器 OS 佈署與 Slurm 角色配置
  hosts: all
  gather_facts: no
  vars:
    slurm_model: "hpc-lab"
    target_os: "ubuntu@24.04"

  tasks:
    - name: 1.1 建立全新 Model
      command: "juju add-model {{ slurm_model }}"
      # [保留] 如果 model 已存在，不報錯繼續往下
      ignore_errors: yes

    - name: 1.2 佈署控制端 (slurmctld)
      command: "juju deploy slurmctld -m {{ slurm_model }} --constraints tags=virtual --base {{ target_os }} --channel=23.11/stable"
      # [新增] 如果應用程式已存在，則視為成功
      register: deploy_ctld
      failed_when: 
        - deploy_ctld.rc != 0 
        - "'already exists' not in deploy_ctld.stderr"

    - name: 1.3 佈署運算端 (slurmd)
      command: "juju deploy slurmd -m {{ slurm_model }} --constraints tags=slurm-node --base {{ target_os }} --channel=23.11/stable"
      # [新增] 同樣處理「已存在」的情況
      register: deploy_d
      failed_when: 
        - deploy_d.rc != 0 
        - "'already exists' not in deploy_d.stderr"

    - name: 1.4 建立連動關係
      command: "juju integrate slurmctld slurmd -m {{ slurm_model }}"
      # [新增] 避免重複建立連動報錯
      ignore_errors: yes

    - name: 1.5 等待服務啟動
      # 既然 status 已經是 active，這步會秒過
      command: "juju wait-for application slurmd -m {{ slurm_model }} --query='status==\"active\"' --timeout 5m0s"

# ==========================================
# 第二場戲：針對 gpu-node01 進行環境注入
# ==========================================
- name: 2. 針對運算節點安裝 580 驅動與監控
  hosts: all
  gather_facts: no
  vars:
    slurm_model: "hpc-lab"

  tasks:
    - name: 2.1 注入今日成功驅動 (v580)
      shell: |
        juju ssh -m {{ slurm_model }} slurmd/0 "
        sudo apt-get update && \
        sudo apt-get install -y nvidia-driver-580 nvidia-utils-580 nvidia-cuda-toolkit"

    - name: 2.2 注入今日成功監控 (v3.3.5)
      shell: |
        juju ssh -m {{ slurm_model }} slurmd/0 "
        # 1. 確保 NVIDIA 倉庫已更新 (預防萬一)
        sudo apt-get update && \
        
        # 2. 安裝 DCGM 引擎
        sudo apt-get install -y datacenter-gpu-manager && \
        
        # 3. [修正] 使用正確的 v3.3.5 下載連結 (注意版本號細節)
        wget https://github.com/NVIDIA/dcgm-exporter/releases/download/v3.3.5-3.4.1/dcgm-exporter_3.3.5-3.4.1_amd64.deb && \
        
        # 4. 安裝並啟動
        sudo dpkg -i dcgm-exporter_3.3.5-3.4.1_amd64.deb && \
        sudo systemctl enable --now dcgm-exporter"
