# ==========================================
# SKU: HPC-Full-Stack-Reconstruction
# ==========================================
- name: 1. 兩台機器 OS 佈署與 Slurm 角色配置
  hosts: all
  gather_facts: no
  vars:
    slurm_model: "hpc-lab"
    target_os: "ubuntu@24.04"

  tasks:
    - name: 1.1 建立全新 Model
      command: "juju add-model {{ slurm_model }}"
      # [保留] 如果 model 已存在，不報錯繼續往下
      ignore_errors: yes

    - name: 1.2 佈署控制端 (slurmctld)
      command: "juju deploy slurmctld -m {{ slurm_model }} --constraints tags=virtual --base {{ target_os }} --channel=23.11/stable"
      # [新增] 如果應用程式已存在，則視為成功
      register: deploy_ctld
      failed_when: 
        - deploy_ctld.rc != 0 
        - "'already exists' not in deploy_ctld.stderr"

    - name: 1.3 佈署運算端 (slurmd)
      command: "juju deploy slurmd -m {{ slurm_model }} --constraints tags=slurm-node --base {{ target_os }} --channel=23.11/stable"
      # [新增] 同樣處理「已存在」的情況
      register: deploy_d
      failed_when: 
        - deploy_d.rc != 0 
        - "'already exists' not in deploy_d.stderr"

    - name: 1.4 建立連動關係
      command: "juju integrate slurmctld slurmd -m {{ slurm_model }}"
      # [新增] 避免重複建立連動報錯
      ignore_errors: yes

    - name: 1.5 等待服務啟動
      # 既然 status 已經是 active，這步會秒過
      command: "juju wait-for application slurmd -m {{ slurm_model }} --query='status==\"active\"' --timeout 5m0s"

# ==========================================
# 第二場戲：針對 gpu-node01 進行環境注入
# ==========================================
- name: 2. 針對運算節點安裝 580 驅動與監控
  hosts: all
  gather_facts: no
  vars:
    slurm_model: "hpc-lab"

  tasks:
    - name: 2.1 基礎環境清理與倉庫設定
      shell: |
        juju ssh -m {{ slurm_model }} slurmd/0 "
        # 徹底移除所有舊版驅動殘留，避免與官方庫衝突
        sudo apt-get purge -y nvidia* libnvidia* && \
        sudo apt-get autoremove -y && \
        
        # 重新導入倉庫
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb && \
        sudo dpkg -i cuda-keyring_1.1-1_all.deb && \
        sudo apt-get update"

    - name: 2.2 安裝官方版 580 驅動與監控
      shell: |
        juju ssh -m {{ slurm_model }} slurmd/0 "
        # 指定安裝官方倉庫的版本
        sudo apt-get install -y nvidia-driver-580 nvidia-utils-580 datacenter-gpu-manager && \
        
        # 下載並安裝監控
        wget https://github.com/NVIDIA/dcgm-exporter/releases/download/v3.3.5-3.4.1/dcgm-exporter_3.3.5-3.4.1_amd64.deb && \
        sudo dpkg -i dcgm-exporter_3.3.5-3.4.1_amd64.deb && \
        sudo systemctl enable --now dcgm-exporter"
