---
- name: 5.4 Fix Member Cluster Monitoring (Auto-generate Kubeconfig)
  hosts: all  # 確保這裡是用 all，讓 Inventory 決定跑哪台
  gather_facts: no
  vars:
    cluster_name: "{{ k8s_cluster | default('hpc-native-cluster') }}"
    # 設定 kubeconfig 的暫存路徑
    member_cluster_kubeconfig: "/tmp/kubeconfig-{{ cluster_name }}"

  tasks:
    # ======================================================
    # 新增步驟：動態從 KubeSphere 抓取並產生 Kubeconfig
    # 這能解決 "找不到檔案" 的問題
    # ======================================================
    - name: 0. 從 Host Cluster 匯出 Member Cluster 的 Kubeconfig
      shell: |
        # 直接從 KubeSphere 的 Cluster 物件中讀取 kubeconfig (Base64 編碼) 並解碼存檔
        kubectl get cluster {{ cluster_name }} -o jsonpath='{.spec.connection.kubeconfig}' | base64 -d > {{ member_cluster_kubeconfig }}
      register: gen_kubeconfig
      
    - name: 0.1 確保 Kubeconfig 產生成功
      fail:
        msg: "無法產生 Kubeconfig，請確認叢集名稱 {{ cluster_name }} 正確且存在於 Host Cluster 中。"
      when: gen_kubeconfig.rc != 0

    # ======================================================
    # 以下是原本的修復邏輯
    # ======================================================
    - name: 1. 等待監控 Namespace 出現 (確保 GUI 安裝已生效)
      shell: |
        kubectl --kubeconfig {{ member_cluster_kubeconfig }} get namespace kubesphere-monitoring-system
      register: ns_check
      until: ns_check.rc == 0
      retries: 20
      delay: 10
      ignore_errors: yes

    - name: 2. 補裝 ServiceMonitor CRD
      shell: |
        kubectl --kubeconfig {{ member_cluster_kubeconfig }} apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.68.0/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
      ignore_errors: yes

    - name: 3. 注入 GPU 採集規則
      shell: |
        cat <<EOF | kubectl --kubeconfig {{ member_cluster_kubeconfig }} apply -f -
        apiVersion: monitoring.coreos.com/v1
        kind: ServiceMonitor
        metadata:
          name: gpu-bridge-monitor
          namespace: kubesphere-monitoring-system
          labels:
            app.kubernetes.io/vendor: kubesphere
        spec:
          selector:
            matchLabels:
              app: dcgm-exporter
          endpoints:
          - port: metrics
            interval: 15s
            path: /metrics
          namespaceSelector:
            matchNames:
            - kubesphere-monitoring-system
        EOF
      register: sm_result

    - name: 4. 清理暫存檔案 (可選，保持環境整潔)
      file:
        path: "{{ member_cluster_kubeconfig }}"
        state: absent
      when: sm_result.rc == 0
