# ========================================================
# PLAY 1: Infrastructure - Deploy K8s (Run:ai Ready)
# 包含: K8s 1.31, StorageClass, Ingress, MetalLB, TLS Secret
# ========================================================
- name: 1. Infrastructure - Deploy Modern Charmed Kubernetes
  hosts: maasjuju
  gather_facts: yes
  vars:
    test_model: "k8s-cluster-runai"
    k8s_channel: "1.31/stable"
    bundle_path: "{{ ansible_user_dir }}/charmed-k8s-runai.yaml"
    
    # [重要] MetalLB IP 設定
    # 請將此處改為你 x86 VM 所在網段的閒置 IP 區間
    # 這些 IP 將被用來指派給 Run:ai Dashboard (Ingress)
    metallb_ip_range: "192.168.64.200-192.168.64.210"

  tasks:
    # --- 1. Environment Cleanup ---
    - name: 1.0 Force cleanup old model
      command: "juju destroy-model {{ test_model }} --no-prompt --force --destroy-storage"
      register: destroy_result
      failed_when: 
        - destroy_result.rc != 0 
        - '"not found" not in destroy_result.stderr'
      ignore_errors: yes

    - name: 1.1 Wait for model release
      pause:
        seconds: 15

    - name: 1.2 Create new Juju Model
      shell: juju add-model {{ test_model }}

    # --- 2. Bundle & Deploy (含 MetalLB & Ingress) ---
    - name: 2.1 Generate Local Bundle
      copy:
        dest: "{{ bundle_path }}"
        mode: '0644'
        content: |
          description: Slinky Modern K8s Cluster (Run:ai Ready)
          base: ubuntu@22.04
          
          machines:
            "0":
              constraints: tags=virtual
            "1":
              constraints: tags=slurm-node
            "2":
              constraints: tags=slurm-node
          
          applications:
            # 核心組件
            easyrsa:
              charm: easyrsa
              channel: latest/stable
              num_units: 1
              to: ["0"]
            etcd:
              charm: etcd
              channel: latest/stable
              num_units: 1
              to: ["0"]
            
            kubernetes-control-plane:
              charm: kubernetes-control-plane
              channel: {{ k8s_channel }}
              num_units: 1
              to: ["0"]
              options:
                allow-privileged: "true"
            
            kubernetes-worker:
              charm: kubernetes-worker
              channel: {{ k8s_channel }}
              num_units: 2
              to: ["1", "2"]
              expose: true
            
            calico:
              charm: calico
              channel: latest/stable
            containerd:
              charm: containerd
              channel: latest/stable
            
            # --- Run:ai 必要組件 ---
            
            # 1. Metrics Server (排程器需要)
            kubernetes-metrics-server:
              charm: kubernetes-metrics-server
              channel: stable
              trust: true
            
            # 2. Ingress Controller (Web UI 入口)
            ingress-nginx-k8s:
              charm: ingress-nginx-k8s
              channel: stable
              trust: true
            
            # 3. MetalLB (提供外部 IP 給 Ingress)
            metallb:
              charm: metallb
              channel: stable
              options:
                iprange: "{{ metallb_ip_range }}"

          relations:
            # K8s 核心連接
            - ["kubernetes-control-plane:kube-control", "kubernetes-worker:kube-control"]
            - ["kubernetes-control-plane:certificates", "easyrsa:client"]
            - ["etcd:certificates", "easyrsa:client"]
            - ["kubernetes-control-plane:etcd", "etcd:db"]
            - ["kubernetes-worker:certificates", "easyrsa:client"]
            - ["calico:etcd", "etcd:db"]
            - ["calico:cni", "kubernetes-control-plane:cni"]
            - ["calico:cni", "kubernetes-worker:cni"]
            - ["containerd:containerd", "kubernetes-worker:container-runtime"]
            - ["containerd:containerd", "kubernetes-control-plane:container-runtime"]
            
            # 監控與 Ingress 連接
            - ["kubernetes-metrics-server:kube-control", "kubernetes-control-plane:kube-control"]
            - ["ingress-nginx-k8s:kube-control", "kubernetes-control-plane:kube-control"]

    - name: 2.2 Deploy Bundle
      shell: |
        juju deploy {{ bundle_path }} --model {{ test_model }} --trust
      register: deploy_out
      until: deploy_out.rc == 0
      retries: 3
      delay: 10

    # --- 3. Infra Monitoring (Wait Loop) ---
    - name: 3.1 Wait for Juju Apps Active
      shell: |
        echo "⏳ Monitoring Juju status (Timeout: 45min)..."
        for i in {1..540}; do
          JSON=$(juju status --model {{ test_model }} --format json)
          # 檢查主要組件
          CP=$(echo "$JSON" | jq -r '.applications["kubernetes-control-plane"]["application-status"].current // "unknown"')
          WK=$(echo "$JSON" | jq -r '.applications["kubernetes-worker"]["application-status"].current // "unknown"')
          
          if [[ "$CP" == "active" && "$WK" == "active" ]]; then
            echo "✅ Core Juju Apps are Active!"
            exit 0
          fi
          if (( i % 12 == 0 )); then echo "   [$i/540] Waiting... (CP=$CP, WK=$WK)"; fi
          sleep 5
        done
        echo "❌ Timeout waiting for Juju apps."
        exit 1
      args:
        executable: /bin/bash
      register: juju_wait
      changed_when: false

    # --- 4. Storage Class Setup ---
    - name: 4.1 Install Local Path Provisioner
      shell: |
        juju ssh --model {{ test_model }} 0 -- \
        "kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.30/deploy/local-path-storage.yaml"
      register: install_sc
      changed_when: "'created' in install_sc.stdout or 'configured' in install_sc.stdout"

    - name: 4.2 Set Default StorageClass
      shell: |
        juju ssh --model {{ test_model }} 0 -- \
        "kubectl patch storageclass local-path -p '{\"metadata\": {\"annotations\":{\"storageclass.kubernetes.io/is-default-class\":\"true\"}}}'"
      register: patch_sc
      changed_when: "'patched' in patch_sc.stdout"

    # --- 5. Run:ai Specific Requirements (TLS & Namespace) ---
    - name: 5.1 Generate TLS Secret for Run:ai
      shell: |
        juju ssh --model {{ test_model }} 0 -- bash -s <<'EOS'
        set -e
        # 1. 建立 Run:ai Backend Namespace (新版強制要求)
        kubectl create namespace runai-backend --dry-run=client -o yaml | kubectl apply -f -
        
        # 2. 產生自簽憑證 (Self-Signed Cert)
        # Run:ai Control Plane 啟動時需要掛載這個 Secret
        openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes \
          -keyout private.pem -out fullchain.pem \
          -subj "/CN=runai.lab.local"
        
        # 3. 建立 Secret (如果不存在)
        if ! kubectl get secret runai-backend-tls -n runai-backend; then
            kubectl create secret tls runai-backend-tls -n runai-backend \
              --cert=fullchain.pem \
              --key=private.pem
            echo "✅ Created TLS Secret: runai-backend-tls"
        else
            echo "ℹ️ TLS Secret already exists."
        fi
        
        # 清理暫存檔
        rm -f private.pem fullchain.pem
        EOS
      register: tls_setup

    # --- 6. Final K8s Health Check ---
    - name: 6.1 Wait for K8s Nodes & System Pods
      shell: |
        juju ssh --model {{ test_model }} 0 -- bash -s <<'EOS'
        set -e
        echo "⏳ Waiting for K8s Nodes & System Pods (Timeout: 15min)..."
        
        # 等待 3 個節點 Ready
        echo "   -> Waiting for 3 nodes to be Ready..."
        for i in {1..60}; do
           READY_COUNT=$(kubectl get nodes --no-headers | grep -w "Ready" | wc -l)
           if [ "$READY_COUNT" -ge 3 ]; then
               echo "   ✅ Found $READY_COUNT Ready nodes."
               break
           fi
           sleep 10
        done
        kubectl wait --for=condition=Ready node --all --timeout=600s

        # 等待系統 Pods
        echo "   -> Waiting for System Pods..."
        kubectl -n kube-system wait pod -l k8s-app=calico-node --for=condition=Ready --timeout=600s
        # 確保 Ingress Controller 取得 LoadBalancer IP
        echo "   -> Waiting for Ingress Controller External IP..."
        sleep 20 # 給 MetalLB 一點時間反應
        kubectl -n ingress-nginx wait deployment/ingress-nginx-controller --for=condition=Available --timeout=300s
        
        echo "✅ K8s Infrastructure is Fully Ready for Run:ai Installation."
        EOS
      changed_when: false
