---
# ========================================================
# SKU: Slinky-SlurmOnK8s-Standardized (Repeatable)
# Goal:
#   1) NFS Server (machine0) + nfs-subdir-external-provisioner + StorageClass
#   2) NVIDIA k8s-device-plugin (Helm) with tolerations + nodeSelector
#   3) cert-manager + slurm-operator-crds + slurm-operator + slurm chart (Slinky)
#
# Pitfalls avoided:
#   - NEVER kubectl patch Controller extraConf (Helm conflict)
#   - Partitions/NodeSet DO NOT depend on Feature
#   - device-plugin MUST have toleration + nodeSelector (GPU taint)
# ========================================================

- name: Application Layer - Deploy Slinky Slurm on K8s (Standardized)
  hosts: maasjuju
  gather_facts: yes

  vars:
    # ---- Reset (run once to return to clean/repeatable state) ----
    reset_before_install: false

    # ---- Juju / machines ----
    test_model: "slinky-cluster"
    machine0: "0"     # control-plane
    machine1: "1"     # gpu worker

    # ---- K8s nodes ----
    controlplane_hostname: "slurmhn"
    gpu_node_hostname: "gpu-node01"

    # ---- Namespaces ----
    ns_certmgr: "cert-manager"
    ns_nvidia: "nvidia-device-plugin"
    ns_slurm_operator: "slinky"
    ns_slurm: "slurm"
    ns_nfs: "nfs-provisioner"

    # ---- NFS ----
    nfs_server_setup: true
    nfs_server: ""                 # empty => machine0_ip
    nfs_export_path: "/srv/nfs/k8s"
    nfs_storageclass: "nfs-rwx"
    nfs_make_default_sc: false
    # å»ºè­°æ”¹æˆä½ çš„ CIDRï¼ˆæ›´å®‰å…¨ï¼‰ï¼›å…ˆç”¨ * æ–¹ä¾¿æ¸¬
    nfs_allow: "*"

    # ---- NVIDIA device plugin ----
    gpu_taint_key: "node-role.anxpert/gpu"
    gpu_taint_value: "true"

    # ---- Versions ----
    cert_manager_chart_version: "v1.19.2"
    slurm_operator_chart_ver: "1.0.1"
    slurm_chart_ver: "1.0.1"

    # ---- Slurm GPU ----
    slurm_gpu_count: 1

  tasks:
    # -----------------------------------------------------------
    # 1) Discover machine IPs
    # -----------------------------------------------------------
    - name: 1.1 Get Juju model status (json)
      shell: "juju status --model {{ test_model }} --format json"
      register: juju_status_raw
      changed_when: false

    - name: 1.2 Parse machine0/machine1 IPv4
      set_fact:
        machine0_ip: "{{ (juju_status_raw.stdout | from_json).machines[machine0]['ip-addresses'] | select('match','^[0-9.]+$') | first }}"
        machine1_ip: "{{ (juju_status_raw.stdout | from_json).machines[machine1]['ip-addresses'] | select('match','^[0-9.]+$') | first }}"

    - name: 1.3 Show discovered IPs
      debug:
        msg:
          - "Machine0 (control-plane) IP: {{ machine0_ip }}"
          - "Machine1 (gpu worker)    IP: {{ machine1_ip }}"

    - name: 1.4 Decide NFS server IP
      set_fact:
        nfs_server_ip: "{{ (nfs_server | trim) if (nfs_server | trim != '') else machine0_ip }}"

    # -----------------------------------------------------------
    # 2) Ensure Helm exists on machine0
    # -----------------------------------------------------------
    - name: 2.1 Install Helm on machine0 if missing
      shell: |
        juju ssh --model {{ test_model }} {{ machine0 }} -- bash -lc '
          set -e
          if ! command -v helm >/dev/null 2>&1; then
            echo "[INFO] Installing Helm..."
            curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          else
            echo "[INFO] Helm already installed"
          fi
        '
      changed_when: false

    # -----------------------------------------------------------
    # 0) Reset (optional)
    # -----------------------------------------------------------
    - name: 0.1 Reset (helm uninstall)
      shell: |
        juju ssh --model {{ test_model }} {{ machine0 }} -- bash -lc '
          set +e
          helm -n {{ ns_slurm }} uninstall slurm 2>/dev/null || true
          helm -n {{ ns_slurm_operator }} uninstall slurm-operator 2>/dev/null || true
          helm -n default uninstall slurm-operator-crds 2>/dev/null || true
          helm -n {{ ns_certmgr }} uninstall cert-manager 2>/dev/null || true
          helm -n {{ ns_nvidia }} uninstall nvidia-device-plugin 2>/dev/null || true
          helm -n {{ ns_nfs }} uninstall nfs-provisioner 2>/dev/null || true
        '
      when: reset_before_install | bool
      changed_when: true

    - name: 0.2 Reset (delete namespaces)
      shell: |
        juju ssh --model {{ test_model }} {{ machine0 }} -- bash -lc '
          set +e
          kubectl delete ns {{ ns_slurm }} --ignore-not-found=true --wait=true || true
          kubectl delete ns {{ ns_slurm_operator }} --ignore-not-found=true --wait=true || true
          kubectl delete ns {{ ns_certmgr }} --ignore-not-found=true --wait=true || true
          kubectl delete ns {{ ns_nvidia }} --ignore-not-found=true --wait=true || true
          kubectl delete ns {{ ns_nfs }} --ignore-not-found=true --wait=true || true
        '
      when: reset_before_install | bool
      changed_when: true

    # -----------------------------------------------------------
    # 3) NFS Server (machine0)
    # -----------------------------------------------------------
    - name: 3.1 Setup NFS server export on machine0 (optional)
      shell: |
        juju ssh --model {{ test_model }} {{ machine0 }} -- bash -lc '
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y nfs-kernel-server
          sudo mkdir -p {{ nfs_export_path }}
          sudo chmod 777 {{ nfs_export_path }}

          EXPORT_LINE="{{ nfs_export_path }} {{ nfs_allow }}(rw,sync,no_subtree_check,no_root_squash)"
          if ! sudo grep -qF "{{ nfs_export_path }}" /etc/exports; then
            echo "$EXPORT_LINE" | sudo tee -a /etc/exports >/dev/null
          fi

          sudo exportfs -ra
          sudo systemctl enable --now nfs-server
          echo "[INFO] exportfs -v:"
          sudo exportfs -v | sed -n "1,120p"
        '
      when: nfs_server_setup | bool
      changed_when: true

    # -----------------------------------------------------------
    # 4) NFS Provisioner (Helm)
    # -----------------------------------------------------------
    - name: 4.1 Create namespace for NFS provisioner
      shell: |
        juju ssh --model {{ test_model }} {{ machine0 }} -- bash -lc '
          kubectl create ns {{ ns_nfs }} --dry-run=client -o yaml | kubectl apply -f -
        '
      changed_when: false

    - name: 4.2 Install/upgrade nfs-subdir-external-provisioner via Helm (NO heredoc)
      shell: |
        juju ssh --model {{ test_model }} {{ machine0 }} -- bash -lc '
          set -euo pipefail
          helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/ >/dev/null 2>&1 || true
          helm repo update >/dev/null 2>&1
    
          helm upgrade --install nfs-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
            -n {{ ns_nfs }} --create-namespace \
            --set nfs.server="{{ nfs_server_ip }}" \
            --set nfs.path="{{ nfs_export_path }}" \
            --set storageClass.name="{{ nfs_storageclass }}" \
            --set storageClass.defaultClass={{ (nfs_make_default_sc | bool) | lower }} \
            --set storageClass.reclaimPolicy=Delete \
            --set storageClass.archiveOnDelete=true
    
          kubectl -n {{ ns_nfs }} rollout status deploy/nfs-provisioner-nfs-subdir-external-provisioner --timeout=240s
        '
      changed_when: true


    # -----------------------------------------------------------
    # 5) NVIDIA device plugin (Helm) with toleration + nodeSelector
    # -----------------------------------------------------------
    - name: 5.1 Create namespace for NVIDIA device plugin
      shell: |
        juju ssh --model {{ test_model }} {{ machine0 }} -- bash -lc '
          kubectl create ns {{ ns_nvidia }} --dry-run=client -o yaml | kubectl apply -f -
        '
      changed_when: false

    - name: 5.2 Install/upgrade NVIDIA device plugin (NO heredoc)
      shell: |
        juju ssh --model {{ test_model }} {{ machine0 }} -- bash -lc '
          set -euo pipefail
          helm repo add nvidia https://nvidia.github.io/k8s-device-plugin >/dev/null 2>&1 || true
          helm repo update >/dev/null 2>&1
    
          helm upgrade --install nvidia-device-plugin nvidia/nvidia-device-plugin \
            -n {{ ns_nvidia }} --create-namespace \
            --set nodeSelector.kubernetes\.io/hostname="{{ gpu_node_hostname }}" \
            --set tolerations[0].key="{{ gpu_taint_key }}" \
            --set tolerations[0].operator="Equal" \
            --set tolerations[0].value="{{ gpu_taint_value }}" \
            --set tolerations[0].effect="NoSchedule"
    
          kubectl -n {{ ns_nvidia }} rollout status ds/nvidia-device-plugin --timeout=240s
        '
      changed_when: true
    

    - name: 5.3 Verify GPU allocatable on gpu node
      shell: |
        juju ssh --model {{ test_model }} {{ machine0 }} -- bash -lc '
          kubectl describe node {{ gpu_node_hostname }} | egrep -i "Taints|nvidia.com/gpu|Allocatable|Capacity" -n || true
        '
      changed_when: false

    - name: 5.4 GPU smoke test pod (NO heredoc, use kubectl run)
      shell: |
        juju ssh --model {{ test_model }} {{ machine0 }} -- bash -lc '
          set -euo pipefail
    
          kubectl -n default delete pod gpu-smoke --ignore-not-found=true >/dev/null 2>&1 || true
    
          kubectl -n default run gpu-smoke \
            --restart=Never \
            --image=nvidia/cuda:12.4.1-base-ubuntu22.04 \
            --overrides='"'"'{
              "apiVersion":"v1",
              "spec":{
                "nodeSelector":{"kubernetes.io/hostname":"{{ gpu_node_hostname }}"},
                "tolerations":[{"key":"{{ gpu_taint_key }}","operator":"Equal","value":"{{ gpu_taint_value }}","effect":"NoSchedule"}],
                "containers":[{
                  "name":"gpu-smoke",
                  "image":"nvidia/cuda:12.4.1-base-ubuntu22.04",
                  "command":["bash","-lc","nvidia-smi -L || true; ls -l /dev/nvidia0 || true; sleep 2"],
                  "resources":{"limits":{"nvidia.com/gpu":1}}
                }]
              }
            }'"'"' \
            --command -- bash -lc "nvidia-smi -L || true; ls -l /dev/nvidia0 || true; sleep 2" >/dev/null 2>&1 || true
    
          kubectl -n default wait --for=condition=Ready pod/gpu-smoke --timeout=180s || true
          kubectl -n default logs gpu-smoke || true
          kubectl -n default delete pod gpu-smoke --ignore-not-found=true >/dev/null 2>&1 || true
        '
      changed_when: true


    # -----------------------------------------------------------
    # 6) cert-manager
    # -----------------------------------------------------------
    - name: 6.1 Create namespace cert-manager
      shell: |
        juju ssh --model {{ test_model }} {{ machine0 }} -- bash -lc '
          kubectl create ns {{ ns_certmgr }} --dry-run=client -o yaml | kubectl apply -f -
        '
      changed_when: false

    - name: 6.2 Install/upgrade cert-manager via Helm
      shell: |
        juju ssh --model {{ test_model }} {{ machine0 }} -- bash -lc '
          set -euo pipefail
          helm repo add jetstack https://charts.jetstack.io >/dev/null 2>&1 || true
          helm repo update >/dev/null 2>&1

          helm upgrade --install cert-manager jetstack/cert-manager \
            -n {{ ns_certmgr }} --create-namespace \
            --version {{ cert_manager_chart_version }} \
            --set crds.enabled=true

          kubectl -n {{ ns_certmgr }} rollout status deploy/cert-manager --timeout=240s
          kubectl -n {{ ns_certmgr }} rollout status deploy/cert-manager-webhook --timeout=240s
          kubectl -n {{ ns_certmgr }} rollout status deploy/cert-manager-cainjector --timeout=240s
        '
      changed_when: true

    # -----------------------------------------------------------
    # 7) slurm-operator-crds + slurm-operator (OCI)
    # -----------------------------------------------------------
    - name: 7.1 Create namespace for slurm operator
      shell: |
        juju ssh --model {{ test_model }} {{ machine0 }} -- bash -lc '
          kubectl create ns {{ ns_slurm_operator }} --dry-run=client -o yaml | kubectl apply -f -
        '
      changed_when: false

    - name: 7.2 Install/upgrade slurm-operator-crds (OCI)
      shell: |
        juju ssh --model {{ test_model }} {{ machine0 }} -- bash -lc '
          set -euo pipefail
          helm upgrade --install slurm-operator-crds oci://ghcr.io/slinkyproject/charts/slurm-operator-crds \
            -n default --create-namespace \
            --version {{ slurm_operator_chart_ver }}
        '
      changed_when: true

    - name: 7.3 Install/upgrade slurm-operator (OCI)
      shell: |
        juju ssh --model {{ test_model }} {{ machine0 }} -- bash -lc '
          set -euo pipefail
          helm upgrade --install slurm-operator oci://ghcr.io/slinkyproject/charts/slurm-operator \
            -n {{ ns_slurm_operator }} --create-namespace \
            --version {{ slurm_operator_chart_ver }}

          kubectl -n {{ ns_slurm_operator }} rollout status deploy/slurm-operator --timeout=240s
        '
      changed_when: true

    # -----------------------------------------------------------
    # 8) slurm chart (OCI) - stable partitions, no Feature dependency
    # -----------------------------------------------------------
    - name: 8.1 Create namespace slurm
      shell: |
        juju ssh --model {{ test_model }} {{ machine0 }} -- bash -lc '
          kubectl create ns {{ ns_slurm }} --dry-run=client -o yaml | kubectl apply -f -
        '
      changed_when: false

    - name: 8.2 Install/upgrade slurm chart (OCI) with stable values (NO heredoc)
      shell: |
        juju ssh --model {{ test_model }} {{ machine0 }} -- bash -lc '
          set -euo pipefail
    
          f=/tmp/slurm-values.yaml
          rm -f "$f"
    
          # --- controller ---
          printf "%s\n" "controller:" >> "$f"
          printf "%s\n" "  extraConf: \"\"" >> "$f"
          printf "%s\n" "  extraConfMap: {}" >> "$f"
          printf "%s\n" "" >> "$f"
    
          # --- nodesets ---
          printf "%s\n" "nodesets:" >> "$f"
          printf "%s\n" "  slinky:" >> "$f"
          printf "%s\n" "    enabled: true" >> "$f"
          printf "%s\n" "    partition:" >> "$f"
          printf "%s\n" "      enabled: false" >> "$f"
          printf "%s\n" "    podSpec:" >> "$f"
          printf "%s\n" "      nodeSelector:" >> "$f"
          printf "%s\n" "        kubernetes.io/hostname: {{ gpu_node_hostname }}" >> "$f"
          printf "%s\n" "        kubernetes.io/os: linux" >> "$f"
          printf "%s\n" "      tolerations:" >> "$f"
          printf "%s\n" "      - effect: NoSchedule" >> "$f"
          printf "%s\n" "        key: {{ gpu_taint_key }}" >> "$f"
          printf "%s\n" "        operator: Equal" >> "$f"
          printf "%s\n" "        value: \"{{ gpu_taint_value }}\"" >> "$f"
          printf "%s\n" "    useResourceLimits: true" >> "$f"
          printf "%s\n" "    slurmd:" >> "$f"
          printf "%s\n" "      resources:" >> "$f"
          printf "%s\n" "        limits:" >> "$f"
          printf "%s\n" "          nvidia.com/gpu: {{ slurm_gpu_count }}" >> "$f"
          printf "%s\n" "      args:" >> "$f"
          printf "%s\n" "      - --conf" >> "$f"
          printf "%s\n" "      - Gres=gpu:{{ slurm_gpu_count }}" >> "$f"
          printf "%s\n" "" >> "$f"
    
          # --- partitions (NO Feature dependency, use ALL) ---
          printf "%s\n" "partitions:" >> "$f"
          printf "%s\n" "  all:" >> "$f"
          printf "%s\n" "    enabled: true" >> "$f"
          printf "%s\n" "    nodesets: [ALL]" >> "$f"
          printf "%s\n" "    configMap:" >> "$f"
          printf "%s\n" "      Default: \"YES\"" >> "$f"
          printf "%s\n" "      MaxTime: UNLIMITED" >> "$f"
          printf "%s\n" "      State: UP" >> "$f"
          printf "%s\n" "  slinky:" >> "$f"
          printf "%s\n" "    enabled: true" >> "$f"
          printf "%s\n" "    nodesets: [ALL]" >> "$f"
          printf "%s\n" "    configMap:" >> "$f"
          printf "%s\n" "      Default: \"NO\"" >> "$f"
          printf "%s\n" "      MaxTime: UNLIMITED" >> "$f"
          printf "%s\n" "      State: UP" >> "$f"
          printf "%s\n" "" >> "$f"
    
          # --- gres.conf ---
          printf "%s\n" "configFiles:" >> "$f"
          printf "%s\n" "  gres.conf: |" >> "$f"
          printf "%s\n" "    AutoDetect=nvidia" >> "$f"
    
          echo "[INFO] Rendered values:"
          sed -n "1,200p" "$f"
    
          helm upgrade --install slurm oci://ghcr.io/slinkyproject/charts/slurm \
            -n {{ ns_slurm }} --create-namespace \
            --version {{ slurm_chart_ver }} \
            -f "$f"
        '
      changed_when: true

    # -----------------------------------------------------------
    # 9) Restart controller + worker (clean re-read)
    # -----------------------------------------------------------
    - name: 9.1 Restart slurm controller + worker pods
      shell: |
        juju ssh --model {{ test_model }} {{ machine0 }} -- bash -lc '
          set -e
          kubectl -n {{ ns_slurm }} delete pod slurm-controller-0 --ignore-not-found=true || true
          kubectl -n {{ ns_slurm }} delete pod slurm-worker-slinky-0 --ignore-not-found=true || true

          kubectl -n {{ ns_slurm }} wait --for=condition=Ready pod/slurm-controller-0 --timeout=300s
          kubectl -n {{ ns_slurm }} wait --for=condition=Ready pod/slurm-worker-slinky-0 --timeout=300s
        '
      changed_when: true

    # -----------------------------------------------------------
    # 10) Verify (inside slurmctld)
    # -----------------------------------------------------------
    - name: 10.1 Verify partitions/nodes/GRES and run GPU job
      shell: |
        juju ssh --model {{ test_model }} {{ machine0 }} -- bash -lc '
          set -e
          echo "== pods =="; kubectl -n {{ ns_slurm }} get pods -o wide; echo

          echo "== sinfo ==";
          kubectl -n {{ ns_slurm }} exec slurm-controller-0 -c slurmctld -- bash -lc \
            '"'"'sinfo -o "%P %a %l %D %t %N"'"'"'
          echo

          echo "== node GRES ==";
          kubectl -n {{ ns_slurm }} exec slurm-controller-0 -c slurmctld -- bash -lc \
            '"'"'scontrol show node slinky-0 | egrep -i "NodeName=|State=|Reason=|Gres=|CfgTRES="'"'"'
          echo

          echo "== srun GPU test (default=all) ==";
          kubectl -n {{ ns_slurm }} exec slurm-controller-0 -c slurmctld -- bash -lc \
            '"'"'srun -N1 -n1 --gres=gpu:{{ slurm_gpu_count }} bash -lc "ls -l /dev/nvidia0 && echo GPU_OK"'"'"'
          echo

          echo "== srun GPU test (partition=slinky) ==";
          kubectl -n {{ ns_slurm }} exec slurm-controller-0 -c slurmctld -- bash -lc \
            '"'"'srun -p slinky -N1 -n1 --gres=gpu:{{ slurm_gpu_count }} bash -lc "ls -l /dev/nvidia0 && echo GPU_OK"'"'"'
        '
      changed_when: false

    - name: Done
      debug:
        msg:
          - "ðŸŽ‰ Standardized Slinky Slurm on K8s deployed"
          - "NFS SC: {{ nfs_storageclass }} (default={{ nfs_make_default_sc }})"
          - "NVIDIA device-plugin: ns={{ ns_nvidia }}, nodeSelector={{ gpu_node_hostname }}, toleration {{ gpu_taint_key }}={{ gpu_taint_value }}"
          - "Slurm: ns={{ ns_slurm }}, partitions: all(default) + slinky, GRES autodetect nvidia"
